title: Arland
email: fredpaletto+arland@gmail.com
description: Arland is a Minecraft server run in a small group format, within a tightknit community of players. Start playing today!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://coffeebank.github.io/arland" # the base hostname & protocol for your site, e.g. http://example.com

feed:
  path: /feed.xml
permalink: /blog/:year:month:day-:title:output_ext

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
